Remove trailing whitespace

diff --git a/linux_kernel_modules/mt7697wifi/scripts/mtwifi b/linux_kernel_modules/mt7697wifi/scripts/mtwifi
--- a/linux_kernel_modules/mt7697wifi/scripts/mtwifi
+++ b/linux_kernel_modules/mt7697wifi/scripts/mtwifi
@@ -20,65 +20,65 @@ mt_wifi_start() {
         sleep 2
     fi
 
-    lsmod | grep 2_mt7697wifi_core >/dev/null                                            
+    lsmod | grep 2_mt7697wifi_core >/dev/null
     if [ $? -eq 1 ]; then
-	hw_itf=`echo $1 | tr '[A-Z]' '[a-z]'`                          
+	hw_itf=`echo $1 | tr '[A-Z]' '[a-z]'`
         insmod /legato/systems/current/modules/2-mt7697wifi_core.ko hw_itf=$hw_itf itf_idx_start=$2 || exit 127
-        echo "Initialized MT7697 WiFi core";                                       
+        echo "Initialized MT7697 WiFi core";
         sleep 2
     fi
-                                                                      
-    ifconfig -a | grep wlan$2 >/dev/null                                         
-    if [ $? -ne 0 ] ; then                                                      
-        echo "Failed to init MT7697 WiFi core"; 
-	exit 127                            
-    fi 
-                                                                         
-    ifconfig wlan$2 up >/dev/null                                                
-    if [ $? -ne 0 ] ; then                                                      
-        echo "Failed to start MT7697 WiFi core"; 
-	exit 127                            
+
+    ifconfig -a | grep wlan$2 >/dev/null
+    if [ $? -ne 0 ] ; then
+        echo "Failed to init MT7697 WiFi core";
+	exit 127
     fi
 
-    echo "Started MT7697 WiFi $1 core wlan$2";                                                                         
-} 
+    ifconfig wlan$2 up >/dev/null
+    if [ $? -ne 0 ] ; then
+        echo "Failed to start MT7697 WiFi core";
+	exit 127
+    fi
 
-mt_wifi_supplicant_stop() { 
+    echo "Started MT7697 WiFi $1 core wlan$2";
+}
+
+mt_wifi_supplicant_stop() {
     echo "Stop MT7697 wpa_supplicant";
     kill `ps -eo pid,args --cols=10000 | awk '/^\/sbin\/wpa_supplicant|-D\s*wext/ && $1 != PROCINFO["pid"] { print $1 }'`
     sleep 2
 }
 
-mt_wifi_stop() {                                           
-    ifconfig | grep wlan$1 >/dev/null                                            
-    if [ $? -eq 0 ]; then                                                       
-       ifconfig wlan$1 down                                                      
+mt_wifi_stop() {
+    ifconfig | grep wlan$1 >/dev/null
+    if [ $? -eq 0 ]; then
+       ifconfig wlan$1 down
     fi
 
-    lsmod | grep 2_mt7697wifi_core >/dev/null                                         
+    lsmod | grep 2_mt7697wifi_core >/dev/null
     if [ $? -eq 0 ]; then
         rmmod 2_mt7697wifi_core || exit 127
-        echo "Removed MT7697 WiFi core"; exit 127         
-    fi                                                             
-}                                                                               
-                                                                                
-case "$1" in                                                                    
-    start)                                                                      
-        mt_wifi_start $2 $3                                                          
-        ;;                                                                      
-    stop) 
-	mt_wifi_supplicant_stop                                                                      
-        mt_wifi_stop $2                                                           
-        ;;                                                                      
-    restart) 
-	mt_wifi_supplicant_stop                                                                   
-        mt_wifi_stop $2                                                          
-        mt_wifi_start $2 $3                                                      
-        ;;                                                                      
-    *)                                                                          
-        exit 1                                                                  
-        ;;        
+        echo "Removed MT7697 WiFi core"; exit 127
+    fi
+}
 
-esac                                                                            
-                                                                                
-exit 0                                                               
+case "$1" in
+    start)
+        mt_wifi_start $2 $3
+        ;;
+    stop)
+	mt_wifi_supplicant_stop
+        mt_wifi_stop $2
+        ;;
+    restart)
+	mt_wifi_supplicant_stop
+        mt_wifi_stop $2
+        mt_wifi_start $2 $3
+        ;;
+    *)
+        exit 1
+        ;;
+
+esac
+
+exit 0
